<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hsforms"
 *
 * Auto generated by Extension Builder 2019-08-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'hotelsuite Forms',
    'description' => 'hotelsuite Forms will show a form to book hotel rooms with some customized configurations.',
    'category' => 'fe',
    'author' => 'Usman Ahmad',
    'author_email' => 'ua@onm.de',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.1.5',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.15-10.4.99',
            'vhs' => '6.0.0-0.0.0'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
