<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hsforms"
 *
 * Auto generated by Extension Builder 2019-08-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'hotelsuite FORMS',
    'description' => 'hotelsuite FORM (hs FORMS) will show a form to book hotel rooms with some customized configurations. This plugin allows the creation of deep links and booking buttons in connection with the Internet booking engine "hotelsuite IBE" (https://www.hotelsuite.de). Sell rooms, vouchers, events, tables and much more! - Get in touch with us: Open New Media GmbH | Digital communication agency | Tel .: +49 261 30380-80 | E-Mail: info@onm.de | Web: https://www.onm.de | Hotel solutions: https://www.hotelsuite.de',
    'category' => 'plugin',
    'author' => 'Usman Ahmad, Tobias Gräber',
    'author_email' => 'ua@onm.de, tg@onm.de',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.1.7',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.15-10.4.99',
            'vhs' => '6.0.0-0.0.0'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
